units:
  kx: cx
  ky: cy
  px: kx + 4
  py: cy + 4
  $default_width: cx
  $default_height: cy
points:
  zones:
    matrix:
      # Fix KiCAD placement
      anchor:
        shift: [100, -100]
      key:
        padding: 1ky
        spread: 1kx
      columns:
        pinky:
          key.column_net: P21
        ring:
          key:
            stagger: 0.4ky
            column_net: P20
        middle:
          key:
            stagger: 0.125ky
            column_net: P19
        index:
          key:
            stagger: -0.125ky
            column_net: P18
        inner:
          key:
            stagger: -0.125ky
            column_net: P15
      rows:
        bottom:
          row_net: P10
        home:
          row_net: P16
        top:
          row_net: P14
    thumbs:
      key:
        padding: 1ky
        spread: 0.75kx
      anchor:
        ref: matrix_index_bottom
        shift: [0.25kx, -1.5ky]
      columns:
        layer:
          key.column_net: P19
        opt:
          key:
            splay: -15
            shift: [0.5kx, 0]
            column_net: P18
        space:
          key:
            splay: -15
            shift: [kx, 0.25ky]
            column_net: P15
      rows:
        cluster:
          row_net: P9
  mirror: &mirror
    ref: thumbs_space_cluster
    distance: 2.5kx

outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_pinky_top
          shift: [0.25px, 0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_ring_top
          shift: [0.25px, 0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [0.5px, 0.5py]
        - ref: matrix_index_top
          shift: [-0.25px, 0.5py]
        - ref: matrix_index_top
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_top
          shift: [-0.25px, 0.5py]
        - ref: matrix_inner_top
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_top
          shift: [1.75px, 0.5py]
        - ref: matrix_inner_bottom
          shift: [1.75px, -py]
        - ref: thumbs_space_cluster
          shift: [0.5px, 0.5py]
        - ref: thumbs_space_cluster
          shift: [0.5px, -0.5py]
        - ref: thumbs_opt_cluster
          shift: [0.5px, -0.5py]
        - ref: thumbs_layer_cluster
          shift: [0.5px, -0.5py]
        - ref: thumbs_layer_cluster
          shift: [-0.5px, -0.5py]
        - ref: matrix_pinky_bottom
          shift: [1.5px, -0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px, -0.5py]
      fillet: 2
  _battery:
    - what: rectangle
      where:
        ref: matrix_inner_bottom
        shift: [0.25kx, -0.75ky]
      size: [60, 35.5]
  combo:
    - name: board
    - operation: subtract
      name: keys
  battery_placement:
    - name: board
    - operation: subtract
      name: _battery

pcbs:
  left:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: /^(matrix|thumbs).*/
        params:
          include_keycap: true
          hotswap: true
          choc_v2_support: false
          include_plated_holes: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: ceoloide/diode_tht_sod123
        where: /^(matrix|thumbs)_.*/
        params:
          reversible: false
          include_traces_vias: true
          include_tht: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      nice_nano:
        what: ceoloide/mcu_nice_nano
        params:
          reversible: false
          reverse_mount: true
        where:
          ref: matrix_inner_top
          shift: [0.95px, -7]
          rotate: 0
      reset:
        what: MJTP1117
        params:
          from: GND
          to: RST
        where:
          ref: matrix_inner_top
          shift: [1.62px, 0]
          rotate: -90
      bat:
        what: ceoloide/battery_connector_jst_ph_2
        params:
          side: F
          reversible: false
          BAT_P: RAW
          BAT_N: GND
        where:
          ref: matrix_inner_top
          shift: [0.95px, -26]
      bat_passthrough:
        what: ceoloide/mounting_hole_npth
        params:
          hole_size: "6"
          hole_drill: "6"
        where:
          ref: matrix_inner_top
          shift: [0.95px, -40]

      # switch:
      #   what: ceoloide/power_switch_smd_side
      #   params:
      #     include_courtyard: true
      #     from: BAT_P
      #     to: RAW
      #   where:
      #     ref: matrix_inner_home
      #     shift: [1.71px, 5]
cases.test:
  - name: combo
    extrude: 1.2
